version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  # Uso de named volumes para mejor persistencia de datos
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
    restart: always  # Asegura que MongoDB se reinicie automáticamente si se detiene inesperadamente

  #mongo-express:
  #  image: mongo-express:latest  # Añade Mongo Express como interfaz gráfica para administrar la base de datos
  #  ports:
  #    - "8081:8081"
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: root123
  #    ME_CONFIG_MONGODB_SERVER: mongodb
  #  depends_on:
  #    - mongodb
  #  restart: always

volumes:
  mongo_data:  # Define el volumen nombrado para persistencia de datos
